   # (
    #     [
    #         Unit("Carbry", 2, 1),
    #         Unit("Yvor", 1, 0),
    #         Unit("Eoin", 2, 0),
    #         Unit("Edwin", 10, 10),
    #     ],
    #     Dragon("Fafnir", 1, 1, 1),
    #     1,
    #     1,
    #     ["Carbry", "Yvor", "Eoin"],
    # ),
    # (
    #     [Unit("Nicholas", 0, 1), Unit("Andrew", -1, 4), Unit("Baran", -6, 5)],
    #     Dragon("Hydra", 0, 0, 2),
    #     0,
    #     1,
    #     ["Nicholas"],
    # ),
    # (
    #     [
    #         Unit("Yvor", 1, 0),
    #         Unit("Nicholas", 0, 1),
    #         Unit("Eoin", 2, 0),
    #         Unit("Cian", 3, 3),
    #         Unit("Andrew", -1, 4),
    #         Unit("Baran", -6, 5),
    #         Unit("Carbry", 2, 1),
    #     ],
    #     Dragon("Smaug", 6, 6, 2),
    #     1,
    #     1,
    #     ["Yvor", "Nicholas", "Eoin", "Cian", "Carbry"],
    # ),